name: Check PullRequest before Merge

on:
  pull_request:
    branches:
      - main

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run tsc
